name: Android Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.0.2"
    - name: Generate Gradle Wrapper if not present
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Find APK Path
      id: find-apk
      run: |
        APK_PATH=$(find app/build -type f -name "*.apk" | head -n 1)
        if [ -z "$APK_PATH" ]; then
          echo "No APK found!"
          exit 1
        fi
        echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        echo "Found APK: $APK_PATH"

    - name: Verify APK exists
      run: |
        if [ ! -f "${{ env.APK_PATH }}" ]; then
          echo "APK not found at ${{ env.APK_PATH }}"
          exit 1
        fi
        echo "APK verified at ${{ env.APK_PATH }}"

    - name: Upload APK to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.APK_PATH }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'v1.0.${{ github.run_number }}'
        releaseName: 'Release v1.0.${{ github.run_number }}'
        draft: false
        prerelease: false

